ALTER TABLE LA_ASSIGN_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_ASSIGN_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE LA_ASSIGN_DETAIL
(
  BILLING_CODE           VARCHAR2(20 BYTE),
  WRITE_OFF_AMOUNT       VARCHAR2(30 BYTE),
  WRITE_OFF_REASON_CODE  VARCHAR2(10 BYTE),
  WRITE_OFF_REASON       VARCHAR2(1000 BYTE),
  DISPUTE_ID             NUMBER,
  DETAIL_ID              NUMBER,
  WRITE_OFF              VARCHAR2(5 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LA_ASSIGN_DETAIL_BILL_CODE ON LA_ASSIGN_DETAIL
(DISPUTE_ID, BILLING_CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX LA_ASSIGN_DETAIL_PK01 ON LA_ASSIGN_DETAIL
(DETAIL_ID)
LOGGING
NOPARALLEL;


ALTER TABLE LA_ASSIGN_DETAIL ADD (
  CONSTRAINT LA_ASSIGN_DETAIL_PK01
  PRIMARY KEY
  (DETAIL_ID)
  USING INDEX LA_ASSIGN_DETAIL_PK01
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_ASSIGN_DETAIL TO RDM_RW;
