DROP TABLE LA_ASSIGNMENT_EMAILS CASCADE CONSTRAINTS;

CREATE TABLE LA_ASSIGNMENT_EMAILS
(
  DISPUTE_ID     NUMBER,
  EMAIL_DATA     BLOB,
  TEAM_NAME      VARCHAR2(300 BYTE),
  MIME_TYPE      VARCHAR2(300 BYTE),
  CHARACTER_SET  VARCHAR2(300 BYTE),
  LAST_UPDATE    DATE,
  DATE_SENT      DATE
)
LOB (EMAIL_DATA) STORE AS (
  TABLESPACE RDM_DATA01
  ENABLE       STORAGE IN ROW
  CHUNK       16384
  RETENTION
  NOCACHE
  LOGGING)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
