ALTER TABLE LA_ASSIGN_HIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_ASSIGN_HIST CASCADE CONSTRAINTS;

CREATE TABLE LA_ASSIGN_HIST
(
  CLIENT_CODE  VARCHAR2(40 BYTE),
  LAST_UPDATE  DATE,
  USER_ID      NUMBER,
  DISPUTE_ID   NUMBER,
  HISTORY_ID   NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LA_ASSIGN_HIST_PK01 ON LA_ASSIGN_HIST
(HISTORY_ID)
LOGGING
NOPARALLEL;


ALTER TABLE LA_ASSIGN_HIST ADD (
  PRIMARY KEY
  (HISTORY_ID)
  USING INDEX LA_ASSIGN_HIST_PK01
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_ASSIGN_HIST TO RDM_RW;
