DROP TABLE LA_ASSIGNMENT_BAK CASCADE CONSTRAINTS;

CREATE TABLE LA_ASSIGNMENT_BAK
(
  INVOICE_NBR             VARCHAR2(20 BYTE),
  IM_ICLEAR_NBR           VARCHAR2(20 BYTE),
  WORKORDER_NBR           VARCHAR2(20 BYTE),
  LOAN_NBR                VARCHAR2(20 BYTE),
  CLIENT_CODE             VARCHAR2(40 BYTE),
  CLIENT_COMMENTS         VARCHAR2(4000 BYTE),
  DISPUTE_AMT             NUMBER,
  INVOICE_AMT             NUMBER,
  WRITE_OFF               VARCHAR2(10 BYTE),
  VENDOR_CODE             VARCHAR2(20 BYTE),
  CHARGE_BACK_AMT_1       VARCHAR2(30 BYTE),
  APPROVAL                VARCHAR2(200 BYTE),
  PENDING_RESEARCH        VARCHAR2(200 BYTE),
  APPEAL                  VARCHAR2(200 BYTE),
  DISPUTE_APPEAL_COMMENT  VARCHAR2(4000 BYTE),
  DEPARTMENT              VARCHAR2(50 BYTE),
  CLIENT_EMPL             VARCHAR2(100 BYTE),
  BUCKET                  VARCHAR2(100 BYTE),
  INVOICE_DATE            DATE,
  X_DISPUTED              VARCHAR2(100 BYTE),
  DISPUTE_TYPE            VARCHAR2(200 BYTE),
  SOURCE_OF_DISPUTE       VARCHAR2(200 BYTE),
  CURTAIL_DATE            DATE,
  LAST_UPDATED            DATE,
  COMMENTS                VARCHAR2(4000 BYTE),
  RECEIVED_DATE           DATE,
  WORK_CODE               VARCHAR2(200 BYTE),
  ADJUSTED_TOTAL          NUMBER,
  MONTH_DATE              VARCHAR2(20 BYTE),
  LOSS_ANALYST            VARCHAR2(1000 BYTE),
  PROCESSOR_ID            NUMBER,
  QUEUE_NAME              VARCHAR2(100 BYTE),
  QUEUE_ID                NUMBER,
  DISPUTE_ID              NUMBER,
  LOAD_DATE               DATE,
  REVIEW_QUEUE            VARCHAR2(40 BYTE),
  ADHOC_INDC              VARCHAR2(200 BYTE),
  REVIEWER_ID             NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON LA_ASSIGNMENT_BAK TO RDM_RW;
