ALTER TABLE LA_ADHOC_QUEUE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_ADHOC_QUEUE CASCADE CONSTRAINTS;

CREATE TABLE LA_ADHOC_QUEUE
(
  USER_ID     NUMBER,
  DISPUTE_ID  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052634.
--  The object is created when the parent object is created.

ALTER TABLE LA_ADHOC_QUEUE ADD (
  PRIMARY KEY
  (DISPUTE_ID)
  ENABLE VALIDATE);
