ALTER TABLE LA_CONTACT_GROUPS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_CONTACT_GROUPS CASCADE CONSTRAINTS;

CREATE TABLE LA_CONTACT_GROUPS
(
  PID            NUMBER,
  CONTACT_GROUP  VARCHAR2(100 BYTE),
  CONTACT_INFO   VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LA_CONTACT_GROUPS_PK01 ON LA_CONTACT_GROUPS
(PID)
LOGGING
NOPARALLEL;


ALTER TABLE LA_CONTACT_GROUPS ADD (
  PRIMARY KEY
  (PID)
  USING INDEX LA_CONTACT_GROUPS_PK01
  ENABLE VALIDATE);
