DROP TABLE LA_COLUMN_LOOKUP CASCADE CONSTRAINTS;

CREATE TABLE LA_COLUMN_LOOKUP
(
  PID             NUMBER,
  COLUMN_NAME     VARCHAR2(100 BYTE),
  COLUMN_HEADING  VARCHAR2(100 BYTE),
  INCLUDE         NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON LA_COLUMN_LOOKUP TO IPP$LIBRARIAN;

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_COLUMN_LOOKUP TO RDM_LOAD;
