ALTER TABLE LA_DEPARTMENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_DEPARTMENTS CASCADE CONSTRAINTS;

CREATE TABLE LA_DEPARTMENTS
(
  DEPARTMENT  VARCHAR2(40 BYTE),
  STATUS      VARCHAR2(10 BYTE),
  PID         NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052645.
--  The object is created when the parent object is created.

ALTER TABLE LA_DEPARTMENTS ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_DEPARTMENTS TO RDM_RW;
