ALTER TABLE LA_EMAIL_ADDRESSES
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_EMAIL_ADDRESSES CASCADE CONSTRAINTS;

CREATE TABLE LA_EMAIL_ADDRESSES
(
  PID            NUMBER,
  CONTACT_GROUP  VARCHAR2(100 BYTE),
  FIRST_NAME     VARCHAR2(100 BYTE),
  LAST_NAME      VARCHAR2(100 BYTE),
  EMAILADDRESS   VARCHAR2(200 BYTE),
  WORKSPACE      VARCHAR2(100 BYTE),
  EMAIL_OPTIONS  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LA_EMAIL_ADDRESSES_PK01 ON LA_EMAIL_ADDRESSES
(PID)
LOGGING
NOPARALLEL;


ALTER TABLE LA_EMAIL_ADDRESSES ADD (
  PRIMARY KEY
  (PID)
  USING INDEX LA_EMAIL_ADDRESSES_PK01
  ENABLE VALIDATE);
