ALTER TABLE LA_EMP_SECURITY
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_EMP_SECURITY CASCADE CONSTRAINTS;

CREATE TABLE LA_EMP_SECURITY
(
  LOGIN          VARCHAR2(25 BYTE),
  STATUS         VARCHAR2(10 BYTE),
  DATA_DATE      DATE,
  USER_ID        NUMBER,
  EMAIL_ADDRESS  VARCHAR2(200 BYTE)             DEFAULT 'noreply@safeguardproperties.com'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052648.
--  The object is created when the parent object is created.

ALTER TABLE LA_EMP_SECURITY ADD (
  PRIMARY KEY
  (USER_ID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_EMP_SECURITY TO RDM_RW;
