ALTER TABLE LA_EMP_SECURITY_LEVELS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_EMP_SECURITY_LEVELS CASCADE CONSTRAINTS;

CREATE TABLE LA_EMP_SECURITY_LEVELS
(
  USER_ID         NUMBER,
  SECURITY_LEVEL  NUMBER,
  STATUS          VARCHAR2(10 BYTE),
  DATA_DATE       DATE,
  PID             NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052649.
--  The object is created when the parent object is created.

ALTER TABLE LA_EMP_SECURITY_LEVELS ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_EMP_SECURITY_LEVELS TO RDM_RW;
