ALTER TABLE LA_FILES_LOADED_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_FILES_LOADED_LIST CASCADE CONSTRAINTS;

CREATE TABLE LA_FILES_LOADED_LIST
(
  PID            NUMBER,
  FILE_TYPE      NUMBER,
  FILE_NAME      VARCHAR2(1000 BYTE),
  RECORDCNT      NUMBER,
  LOAD_DATE      DATE,
  LOADED_BY      VARCHAR2(100 BYTE),
  COMMENTS       VARCHAR2(1000 BYTE),
  BEGIN_LOAD_ID  NUMBER,
  END_LOAD_ID    NUMBER,
  LOADED         NUMBER                         DEFAULT 0,
  PROCESS_NO     NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052651.
--  The object is created when the parent object is created.

ALTER TABLE LA_FILES_LOADED_LIST ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_FILES_LOADED_LIST TO IPP$LIBRARIAN;

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_FILES_LOADED_LIST TO RDM_RW;
