ALTER TABLE LA_FILE_TYPES
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_FILE_TYPES CASCADE CONSTRAINTS;

CREATE TABLE LA_FILE_TYPES
(
  PID         NUMBER,
  FILE_TYPE   VARCHAR2(200 BYTE),
  COMMENTS    VARCHAR2(1000 BYTE),
  PAGE_NO     NUMBER,
  PROCESS_NO  NUMBER,
  PAGE_ITEM   VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052650.
--  The object is created when the parent object is created.

ALTER TABLE LA_FILE_TYPES ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_FILE_TYPES TO RDM_RW;
