ALTER TABLE LA_OUTSTANDING_ADJUSTED_STG
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_OUTSTANDING_ADJUSTED_STG CASCADE CONSTRAINTS;

CREATE TABLE LA_OUTSTANDING_ADJUSTED_STG
(
  INVOICE_NBR      VARCHAR2(200 BYTE),
  VENDOR           VARCHAR2(200 BYTE),
  VENDOR_CONTACT   VARCHAR2(200 BYTE),
  LOAN_NBR         VARCHAR2(100 BYTE),
  INVOICE_DATE     VARCHAR2(30 BYTE),
  DEPT             VARCHAR2(10 BYTE),
  STATE            VARCHAR2(10 BYTE),
  BORROWER         VARCHAR2(100 BYTE),
  ADJUSTED_TOTAL   VARCHAR2(30 BYTE),
  EARLIEST_ADJ_DT  VARCHAR2(30 BYTE),
  CURTAIL_DATE     VARCHAR2(30 BYTE),
  PID              NUMBER,
  LOAD_ID          NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052657.
--  The object is created when the parent object is created.

ALTER TABLE LA_OUTSTANDING_ADJUSTED_STG ADD (
  PRIMARY KEY
  (LOAD_ID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_OUTSTANDING_ADJUSTED_STG TO IPP$LIBRARIAN;

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_OUTSTANDING_ADJUSTED_STG TO RDM_RW;
