ALTER TABLE LA_PENDING_RESEARCH
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_PENDING_RESEARCH CASCADE CONSTRAINTS;

CREATE TABLE LA_PENDING_RESEARCH
(
  PENDING_ACTION  VARCHAR2(40 BYTE),
  STATUS          VARCHAR2(10 BYTE),
  PID             NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052665.
--  The object is created when the parent object is created.

ALTER TABLE LA_PENDING_RESEARCH ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_PENDING_RESEARCH TO RDM_RW;
