DROP TABLE LA_PROCESS_FILES CASCADE CONSTRAINTS;

CREATE TABLE LA_PROCESS_FILES
(
  PID           NUMBER,
  PROCESS_TYPE  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
