ALTER TABLE LA_PENDING_REJECTIONS_AUD
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_PENDING_REJECTIONS_AUD CASCADE CONSTRAINTS;

CREATE TABLE LA_PENDING_REJECTIONS_AUD
(
  ACTION_TAKEN       VARCHAR2(200 BYTE),
  SERVICER           VARCHAR2(200 BYTE),
  LOAN_NBR           VARCHAR2(30 BYTE),
  INVOICE_TYPE       VARCHAR2(100 BYTE),
  INVOICE_DATE       VARCHAR2(30 BYTE),
  INVOICE_NBR        VARCHAR2(30 BYTE),
  ORDER_NBR          VARCHAR2(30 BYTE),
  STATE              VARCHAR2(100 BYTE),
  SERVICER_COMMENTS  VARCHAR2(4000 BYTE),
  COMMENTS_DATE      VARCHAR2(30 BYTE),
  EXPIRES_IN         VARCHAR2(10 BYTE),
  INVOICE_AMT        VARCHAR2(30 BYTE),
  LOAD_ID            NUMBER,
  FILE_ID            NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052663.
--  The object is created when the parent object is created.

ALTER TABLE LA_PENDING_REJECTIONS_AUD ADD (
  PRIMARY KEY
  (LOAD_ID)
  ENABLE VALIDATE);
