DROP TABLE LA_PENDING_CONVERT CASCADE CONSTRAINTS;

CREATE TABLE LA_PENDING_CONVERT
(
  LOAD_ID            NUMBER,
  CLIENT_CODE        VARCHAR2(300 BYTE),
  INVOICE_NBR        VARCHAR2(300 BYTE),
  INVOICE_NBR_SHORT  VARCHAR2(400 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON LA_PENDING_CONVERT TO RDM_RW;
