DROP TABLE LA_QUEUE_PROCESSORS CASCADE CONSTRAINTS;

CREATE TABLE LA_QUEUE_PROCESSORS
(
  LOGIN   VARCHAR2(25 BYTE),
  STATUS  VARCHAR2(10 BYTE),
  PID     NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON LA_QUEUE_PROCESSORS TO RDM_RW;
