DROP TABLE LA_QUEUE_PROCESSOR_ALT CASCADE CONSTRAINTS;

CREATE TABLE LA_QUEUE_PROCESSOR_ALT
(
  PROCESSORS_PID  NUMBER,
  PID             NUMBER,
  PICK_ORDER      NUMBER,
  LOGIN           VARCHAR2(25 BYTE),
  STATUS          VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ALT_PROCESSOR_IDX ON LA_QUEUE_PROCESSOR_ALT
(PROCESSORS_PID, PID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ALT_PROCESSOR_POS ON LA_QUEUE_PROCESSOR_ALT
(PROCESSORS_PID, PICK_ORDER)
LOGGING
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON LA_QUEUE_PROCESSOR_ALT TO RDM_RW;
