ALTER TABLE LA_REPORT_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_REPORT_LIST CASCADE CONSTRAINTS;

CREATE TABLE LA_REPORT_LIST
(
  REPORT_ID               NUMBER,
  REPORT_NAME             VARCHAR2(300 BYTE),
  REPORT_USE              VARCHAR2(300 BYTE),
  AUTO_CREATE             NUMBER,
  SENT_OUT                NUMBER,
  CONTACT_GROUP           VARCHAR2(100 BYTE),
  EOM                     NUMBER,
  DAILY                   NUMBER,
  STORE_AT                VARCHAR2(300 BYTE),
  ALL_COLUMNS             NUMBER,
  ADJUSTED_TOTAL          VARCHAR2(10 BYTE),
  APPEAL                  VARCHAR2(10 BYTE),
  APPROVAL                VARCHAR2(10 BYTE),
  BUCKET                  VARCHAR2(10 BYTE),
  CHARGE_BACK_AMT_1       VARCHAR2(10 BYTE),
  CLIENT_CODE             VARCHAR2(10 BYTE),
  CLIENT_COMMENTS         VARCHAR2(10 BYTE),
  CLIENT_EMPL             VARCHAR2(10 BYTE),
  COMMENTS                VARCHAR2(10 BYTE),
  CURTAIL_DATE            VARCHAR2(10 BYTE),
  DEPARTMENT              VARCHAR2(10 BYTE),
  DISPUTE_AMT             VARCHAR2(10 BYTE),
  DISPUTE_APPEAL_COMMENT  VARCHAR2(10 BYTE),
  DISPUTE_TYPE            VARCHAR2(10 BYTE),
  IM_ICLEAR_NBR           VARCHAR2(10 BYTE),
  INVOICE_AMT             VARCHAR2(10 BYTE),
  INVOICE_DATE            VARCHAR2(10 BYTE),
  INVOICE_NBR             VARCHAR2(10 BYTE),
  LAST_UPDATED            VARCHAR2(10 BYTE),
  LOAN_NBR                VARCHAR2(10 BYTE),
  LOSS_ANALYST            VARCHAR2(10 BYTE),
  MONTH_DATE              VARCHAR2(10 BYTE),
  PENDING_RESEARCH        VARCHAR2(10 BYTE),
  RECEIVED_DATE           VARCHAR2(10 BYTE),
  SOURCE_OF_DISPUTE       VARCHAR2(10 BYTE),
  VENDOR_CODE             VARCHAR2(10 BYTE),
  WORKORDER_NBR           VARCHAR2(10 BYTE),
  WORK_CODE               VARCHAR2(10 BYTE),
  WRITE_OFF               VARCHAR2(10 BYTE),
  X_DISPUTED              VARCHAR2(10 BYTE),
  EOW                     NUMBER,
  REPORT_PAGE             NUMBER,
  REPORT_ORDER            VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052667.
--  The object is created when the parent object is created.

ALTER TABLE LA_REPORT_LIST ADD (
  PRIMARY KEY
  (REPORT_ID)
  ENABLE VALIDATE);
