ALTER TABLE LA_RESOLUTION_PENDING_STG
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_RESOLUTION_PENDING_STG CASCADE CONSTRAINTS;

CREATE TABLE LA_RESOLUTION_PENDING_STG
(
  CLIENT               VARCHAR2(200 BYTE),
  INVOICE_NBR          VARCHAR2(200 BYTE),
  ORDER_NBR            VARCHAR2(100 BYTE),
  VENDOR_CONTACT       VARCHAR2(100 BYTE),
  LOAN_NBR             VARCHAR2(100 BYTE),
  INVOICE_DATE         VARCHAR2(100 BYTE),
  DEPT                 VARCHAR2(10 BYTE),
  STATE                VARCHAR2(10 BYTE),
  RESOLUTION_TYPE      VARCHAR2(30 BYTE),
  INVOICE_AMT          VARCHAR2(20 BYTE),
  VENDOR_COMMENT       VARCHAR2(4000 BYTE),
  VENDOR_DATE          VARCHAR2(30 BYTE),
  CLIENT_COMMENT       VARCHAR2(4000 BYTE),
  CLIENT_DATE          VARCHAR2(30 BYTE),
  REASON               VARCHAR2(200 BYTE),
  RESOLUTION_DEADLINE  VARCHAR2(30 BYTE),
  CURTAIL_DATE         VARCHAR2(30 BYTE),
  PID                  NUMBER,
  LOAD_ID              NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052669.
--  The object is created when the parent object is created.

ALTER TABLE LA_RESOLUTION_PENDING_STG ADD (
  PRIMARY KEY
  (LOAD_ID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_RESOLUTION_PENDING_STG TO IPP$LIBRARIAN;

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_RESOLUTION_PENDING_STG TO RDM_RW;
