DROP TABLE LA_RESOLUTION_PENDING_AUD CASCADE CONSTRAINTS;

CREATE TABLE LA_RESOLUTION_PENDING_AUD
(
  ACTION_TAKEN         VARCHAR2(100 BYTE),
  CLIENT               VARCHAR2(200 BYTE),
  INVOICE_NBR          VARCHAR2(200 BYTE),
  ORDER_NBR            VARCHAR2(100 BYTE),
  VENDOR_CONTACT       VARCHAR2(100 BYTE),
  LOAN_NBR             VARCHAR2(100 BYTE),
  INVOICE_DATE         VARCHAR2(100 BYTE),
  DEPT                 VARCHAR2(10 BYTE),
  STATE                VARCHAR2(10 BYTE),
  RESOLUTION_TYPE      VARCHAR2(30 BYTE),
  INVOICE_AMT          VARCHAR2(20 BYTE),
  VENDOR_COMMENT       VARCHAR2(4000 BYTE),
  VENDOR_DATE          VARCHAR2(20 BYTE),
  CLIENT_COMMENT       VARCHAR2(4000 BYTE),
  CLIENT_DATE          VARCHAR2(30 BYTE),
  REASON               VARCHAR2(200 BYTE),
  RESOLUTION_DEADLINE  VARCHAR2(30 BYTE),
  CURTAIL_DATE         VARCHAR2(30 BYTE),
  PID                  NUMBER,
  LOAD_ID              NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON LA_RESOLUTION_PENDING_AUD TO RDM_RW;
