ALTER TABLE LA_SOURCE_OF_DISPUTE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_SOURCE_OF_DISPUTE CASCADE CONSTRAINTS;

CREATE TABLE LA_SOURCE_OF_DISPUTE
(
  SOURCE_OF_DISPUTE  VARCHAR2(100 BYTE),
  STATUS             VARCHAR2(10 BYTE),
  PID                NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052671.
--  The object is created when the parent object is created.

ALTER TABLE LA_SOURCE_OF_DISPUTE ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_SOURCE_OF_DISPUTE TO RDM_RW;
