ALTER TABLE LA_SECURITY_LEVELS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_SECURITY_LEVELS CASCADE CONSTRAINTS;

CREATE TABLE LA_SECURITY_LEVELS
(
  PID             NUMBER,
  SECURITY_TITLE  VARCHAR2(200 BYTE),
  SECURITY_LEVEL  NUMBER,
  ACTIVE          NUMBER,
  DATA_DATE       DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052670.
--  The object is created when the parent object is created.

ALTER TABLE LA_SECURITY_LEVELS ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT SELECT ON LA_SECURITY_LEVELS TO IPP$LIBRARIAN;

GRANT SELECT ON LA_SECURITY_LEVELS TO RDM_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_SECURITY_LEVELS TO RDM_RW;
