ALTER TABLE LA_VALIDATION_STG
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_VALIDATION_STG CASCADE CONSTRAINTS;

CREATE TABLE LA_VALIDATION_STG
(
  LOAD_ID      NUMBER,
  CLIENT_CODE  VARCHAR2(40 BYTE),
  LA_HIGH      VARCHAR2(200 BYTE),
  LA_LOW       VARCHAR2(200 BYTE),
  FILE_ID      NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052675.
--  The object is created when the parent object is created.

ALTER TABLE LA_VALIDATION_STG ADD (
  PRIMARY KEY
  (LOAD_ID)
  ENABLE VALIDATE);
