ALTER TABLE LA_VALIDATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_VALIDATION CASCADE CONSTRAINTS;

CREATE TABLE LA_VALIDATION
(
  PID          NUMBER,
  CLIENT_CODE  VARCHAR2(40 BYTE),
  LA_HIGH      VARCHAR2(200 BYTE),
  LA_LOW       VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052673.
--  The object is created when the parent object is created.

ALTER TABLE LA_VALIDATION ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);
