ALTER TABLE LA_VALIDATION_CODES
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_VALIDATION_CODES CASCADE CONSTRAINTS;

CREATE TABLE LA_VALIDATION_CODES
(
  CODE       VARCHAR2(20 BYTE),
  LA_ERRORS  VARCHAR2(200 BYTE),
  STATUS     VARCHAR2(10 BYTE),
  PID        NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052674.
--  The object is created when the parent object is created.

ALTER TABLE LA_VALIDATION_CODES ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_VALIDATION_CODES TO RDM_RW;
