ALTER TABLE LA_WRITE_OFF
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_WRITE_OFF CASCADE CONSTRAINTS;

CREATE TABLE LA_WRITE_OFF
(
  WRITE_OFF  VARCHAR2(10 BYTE),
  STATUS     VARCHAR2(10 BYTE),
  PID        NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052676.
--  The object is created when the parent object is created.

ALTER TABLE LA_WRITE_OFF ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_WRITE_OFF TO RDM_RW;
