ALTER TABLE LA_WRITE_OFF_ERRORS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_WRITE_OFF_ERRORS CASCADE CONSTRAINTS;

CREATE TABLE LA_WRITE_OFF_ERRORS
(
  WRITE_OFF_CODE   VARCHAR2(20 BYTE),
  WRITE_OFF_ERROR  VARCHAR2(200 BYTE),
  STATUS           VARCHAR2(10 BYTE),
  PID              NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0052677.
--  The object is created when the parent object is created.

ALTER TABLE LA_WRITE_OFF_ERRORS ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON LA_WRITE_OFF_ERRORS TO RDM_RW;
